name: axOS Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Toolchain
      run: |
        sudo apt-get update
        # 도구 쓰기 위해 패키지 설치
        sudo apt-get install -y gcc-aarch64-linux-gnu make binutils-aarch64-linux-gnu

    - name: Build Kernel
      run: |
        make all

    - name: Verify Build Output
      run: |
        # kernel8.img 생성확인
        if [ -f build/kernel8.img ]; then
          echo "Build Success: build/kernel8.img exists."
          ls -l build/kernel8.img
        else
          echo "Build Failed: Output file not found."
          exit 1
        fi
